export const LightColors = {
  background: '#8fbea7',
  primary: '#448866',
  formBackground: '#f2f2f2',
  itemBorder: '#f2f2f2',
  darkBackground: '#222222',
  formFocus: '#f8f8f8',
  formHover: '#efefef',
  grey: '#888888',
  white: '#ffffff',
  black: '#000000',
  divider: '#dddddd',
  mask: '#dddddd',
  encircle: '#cccccc',
  alert: '#ff8888',
  warn: '#dd4444',
  enabled: '#444444',
  disabled: '#aaaaaa',
  text: '#444444',
  link: '#0077CC',

  itemDivider: '#eeeeee',
  
  connected: '#44cc44',
  connecting: '#dd88ff',
  requested: '#4488ff',
  pending: '#22aaaa',
  confirmed: '#aaaaaa',
  error: '#ff4444',

  profileForm: '#e8e8e8',
  profileDivider: '#aaaaaa',
  statsForm: '#ededed',
  statsDivider: '#afafaf',
  channel: '#f2f2f2',
  card: '#eeeeee',

  selectHover: '#fafafa',
};

export const DarkColors = {
  background: '#8fbea7',
  primary: '#448866',
  formBackground: '#222222',
  itemBorder: '#aaaaaa',
  darkBackground: '#222222',
  formFocus: '#444444',
  formHover: '#efefef',
  grey: '#888888',
  white: '#ffffff',
  black: '#000000',
  divider: '#eeeeee',
  mask: '#dddddd',
  encircle: '#cccccc',
  alert: '#ff8888',
  warn: '#dd4444',
  enabled: '#444444',
  disabled: '#aaaaaa',
  text: '#eeeeee',
  link: '#0077CC',

  itemDivider: '#eeeeee',
  
  connected: '#44cc44',
  connecting: '#dd88ff',
  requested: '#4488ff',
  pending: '#22aaaa',
  confirmed: '#aaaaaa',
  error: '#ff4444',

  profileForm: '#e8e8e8',
  profileDivider: '#aaaaaa',
  statsForm: '#ededed',
  statsDivider: '#afafaf',
  channel: '#f2f2f2',
  card: '#eeeeee',

  selectHover: '#fafafa',
};

export default LightColors;
